- id: doi:10.1016/j.materresbull.2025.113339
  type: paper
  description: Image guided therapeutics, a multimodal approach in cancer treatment where combinatorial imaging and therapy in a single system, has become highly pertinent contemporary chemotherapeutic approach. Herein, a bismuth/Fe3O4 metal organic framework nanocomposite system (BiTP/ Fe3O4) having high X-ray visibility (2981.8 HU) and saturation magnetization prepared by in situ synthesis is presented for computed tomography based imaging and magnetic hyperthermia therapy. Surface anchored Fe3O4 nanoparticles on MOF crystals enable magnetic targeting in the presence of external magnetic field and exhibit hyperthermia potential while bismuth serve as a potential contrast agent due to its intrinsic radiopaque properties. The synergistic effect generated in a single system has a hyperthermia time-temperature profile (42. 1 °C within 7 min) and X-ray visibility. Cytocompatibility of the system has been verified by MTT and live dead assay. Preferential uptake of BiTP/Fe3O4 by Human osteosarcoma cells was affirmed by prussian blue staining, which further benefits to the hyperthermia treatment.
  date: 2025-6-1
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0025540825000479-ga1.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.sciencedirect.com/science/article/pii/S0025540825000479

- id: doi:10.1016/j.ijbiomac.2024.130209
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0141813024010122-ga1.jpg

- id: doi:10.1016/j.phyplu.2024.100668
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0141813024010122-ga1.jpg

- id: doi:10.1021/acsapm.3c01654
  image: https://pubs.acs.org/cms/10.1021/acsapm.3c01654/asset/images/medium/ap3c01654_0010.gif

- id: doi:10.1016/j.jlumin.2023.119899
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0022231323002326-ga1.jpg

- title: Aqueous Cissus quadrangularis Stem Extract Integrated Biodegradable Tissue Engineering Scaffold Augments Early Biomimetic and Biomineralization In Vitroe
  authors:
    - Praseetha R. Nair 
    - S. Sreeja
    - G. S. Sailaja
  publisher: The Society for Biomaterials and Artificial Organs (India)
  date: 2023-06-30
  link: https://www.biomaterials.org.in/tibao/index.php/tibao/article/view/135/58

- id: doi:10.1039/D3TC01033C
  image: https://pubs.rsc.org/image/article/2023/TC/d3tc01033c/d3tc01033c-f1.gif

- id: doi:10.1016/j.bioadv.2022.213137
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2772950822004149-ga1.jpg

- id: doi:10.1016/j.matlet.2020.127365
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0167577X20300707-ga1.jpg

- id: doi:10.1016/j.reactfunctpolym.2022.105190
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1381514822000323-ga1.jpg

- id: doi:10.1039/D2NJ00288D
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D2NJ00288D&imageInfo.ImageIdentifier.Year=2022

- id: doi:10.1007/s10570-021-04288-6
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs10570-021-04288-6/MediaObjects/10570_2021_4288_Figa_HTML.png?as=webp

- id: doi:10.1007/s12038-021-00206-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs12038-021-00206-x/MediaObjects/12038_2021_206_Figa_HTML.png?as=webp

- id: doi:10.1016/j.matchemphys.2021.125108
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0254058421008919-ga1.jpg

- id: doi:10.1021/acsomega.1c02303
  image: https://pubs.acs.org/cms/10.1021/acsomega.1c02303/asset/images/medium/ao1c02303_0013.gif

- id: doi:10.1093/mtomcs/mfab049
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/metallomics/13/8/10.1093_mtomcs_mfab049/2/m_mfab049gra.jpeg?Expires=1785322026&Signature=HXN~-xj47oLoNRaGB3R~35rNkybz6BHhQGXgCTV3-ClJB8ZhSwrItPc1SDtwEHjtJPJgap35dIcxcXDE~L~wEJSe1TAmeq5KiJM0W35ecjzpYdRaW6uvF81ByJtXAJ6hgpiq5csroanILHb5EYaHVAaTAmM2AkZdACWRO-msCkRrkGy~T0-EU7kxEnqPbnBmVStriA7tGMyUo3wSWhMUV0YsVBC3KXswtBE5C6n2ScMfbiVW8NFqVTxd7Hs6~gUme~8XJHIpN2TnABrh0aYjGb3MQ~Zqu6Q0Nnz-5oHxbc7c9v3HyWajBajz7gaHPb2hvyf3FSaKCE3ACB9dy2HAdQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1039/D1NJ03687D
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D1NJ03687D&imageInfo.ImageIdentifier.Year=2021

- id: doi:10.1039/D1BM01316E
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D1BM01316E&imageInfo.ImageIdentifier.Year=2021

- id: doi:10.1021/acsbiomaterials.0c01628
  image: https://pubs.acs.org/cms/10.1021/acsbiomaterials.0c01628/asset/images/medium/ab0c01628_0016.gif

- id: doi:10.1016/j.msec.2019.110491
  image: https://ars.els-cdn.com/content/image/1-s2.0-S092849311932908X-ga1.jpg

- id: doi:10.1016/j.matlet.2020.127365
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0167577X20300707-ga1.jpg

- id: doi:10.1039/D1NJ01262B
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D1NJ01262B&imageInfo.ImageIdentifier.Year=2021

- id: doi:10.1039/D1NJ01913A
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D1NJ01913A&imageInfo.ImageIdentifier.Year=2021

- id: doi:10.1039/D1TB01513C
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D1TB01513C&imageInfo.ImageIdentifier.Year=2021

- id: doi:10.1039/C5PY01058F
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C5PY01058F&imageInfo.ImageIdentifier.Year=2015

- id: doi:10.1021/acsami.5b00532
  image: https://pubs.acs.org/cms/10.1021/acsami.5b00532/asset/images/medium/am-2015-00532m_0005.gif

- id: doi:10.1186/s12929-016-0284-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12929-016-0284-x/MediaObjects/12929_2016_284_Fig1_HTML.gif?

- id: doi:10.1002/slct.201701416
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/0e6d21a8-0a14-4187-a003-0c98588d640f/slct201701416-toc-0001-m.png

- id: doi:10.1039/C8NJ03170C
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C8NJ03170C&imageInfo.ImageIdentifier.Year=2018

- id: doi:10.1039/C8CY02232A
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C8CY02232A&imageInfo.ImageIdentifier.Year=2019

- id: doi:10.1039/C9NJ05343C
  image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=C9NJ05343C&imageInfo.ImageIdentifier.Year=2020

- id: doi:10.1039/C3TA13540C
  image: https://pubs.rsc.org/image/article/2014/TA/c3ta13540c/c3ta13540c-f5.gif

- id: doi:10.1007/s10856-010-3987-7
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1007%2Fs10856-010-3987-7/MediaObjects/10856_2010_3987_Fig7_HTML.gif?

- id: doi:10.1002/app.34157
  image: https://onlinelibrary.wiley.com/cms/asset/69cbe8fe-294b-4cbd-994a-4cfd6e87d1ed/mfig003.jpg

- id: doi:10.1158/1538-7445.AM2012-4992
  image: 

- id: doi:10.1158/1538-7445.AM2012-4758
  image: 

- id: doi:10.1007/s10456-012-9301-1
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1007%2Fs10456-012-9301-1/MediaObjects/10456_2012_9301_Fig5_HTML.gif?

- id: doi:10.3892/ijo.2012.1678
  image: https://www.spandidos-publications.com/article_images/ijo/42/1/IJO-42-01-0188-g00.jpg

- id: doi:10.1002/jbm.b.30725
  image: https://onlinelibrary.wiley.com/cms/asset/7a3643e7-525a-4d8b-9006-3381b8cb4e0c/mfig003.jpg

- id: doi:10.1089/ten.tea.2008.0454
  image: 

- id: doi:10.1016/j.actbio.2008.12.005
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1742706108003826-gr3.jpg

- id: doi:10.1089/ten.tea.2008.0454
  image: 

- id: doi:10.1023/A:1025689701309
  image: 

- id: doi:10.4028/www.scientific.net/KEM.309-311.493
  image: https://www.scientific.net/Image/TitleCover/542?width=190

- id: doi:10.1002/app.23058
  image: https://onlinelibrary.wiley.com/cms/asset/4be92469-51bf-4775-8776-a6bb4e9bc41a/mfig001.jpg

- title: Biomimetically modified Poly (2-hydroxy ethyl methacrylate-co-methyl methacrylate) microspheres for bone augmentation
  authors:
    - Sailaja G. S.
    - Kumary T. V.
    - Varma H. K.
  publisher: Society for Biomaterials and Artificial Organs
  date: 2006-07-30
  link: https://link.gale.com/apps/doc/A165363943/HRCA

- id: doi:10.1016/j.actbio.2006.05.011
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1742706106000626-gr7.sml
